# Copyright 2011 Dylan Maxwell. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=config
GOFILES=\
	file.go\
	props.go\

include $(GOROOT)/src/Make.pkg
